### ISSUE TITLE
Did you see the 2017-11-14 F16j MATS table bios update?

### ISSUE THREAD

**Issue by RamKromberg** [theracermaster/coreboot_mainboard_gigabyte_ga-z77x-ud5h#2]
Not really an issue, but I think you have fans at gigabyte :D

**Comment by al3xtjames** [comment]
lol, I saw that. I wonder if they [looked at my post](https://alextjam.es/debugging-appleacpiplatform/). Looks like they simply replaced the unprintable char (`'\x98'`) with a space (`'\x20'`).

**Comment by RamKromberg** [comment]
> I wonder if they looked at my post.

It's absolutely certain. I went through their entire socket 1155 z77 board list ( https://www.gigabyte.com/Motherboard/Socket-1155 filter z77 ) and only the UD5Hs received this fix:

Updated tables:
GA-Z77X-UD5H-WB WIFI (rev. 1.0)
GA-Z77X-UD5H-WB WIFI (rev. 1.1)
GA-Z77X-UD5H (rev. 1.0)
GA-Z77X-UD5H (rev. 1.1)

Not updated:
G1.Sniper 3 (rev. 1.0)
G1.Sniper M3 (rev. 1.0)
GA-Z77X-UP7 (rev. 1.0)
GA-Z77X-UP5 TH (rev. 1.0)
GA-Z77X-UP4 TH (rev. 1.0)
GA-Z77X-UD4H (rev. 1.0) 
GA-Z77X-UD3H-WB WIFI (rev. 1.0) 
GA-Z77X-UD3H (rev. 1.0)
GA-Z77X-UD3H (rev. 1.1)
GA-Z77X-UD3H (rev. 1.2)
GA-Z77X-D3H (rev. 1.0)
GA-Z77X-D3H (rev. 1.1)
GA-Z77X-D3H (rev. 1.2)
GA-Z77-HD4 (rev. 1.0)
GA-Z77-HD3 (rev. 1.0)
GA-Z77-D3H (rev. 1.0)
GA-Z77-D3H (rev. 1.1)
GA-Z77-D3H (rev. 1.2)
GA-Z77-DS3H (rev. 1.0)
GA-Z77-DS3H (rev. 1.1)
GA-Z77P-D3 (rev. 1.0)
GA-Z77P-D3 (rev. 1.1)
GA-Z77MX-D3H TH (rev. 1.0)
GA-Z77MX-D3H (rev. 1.0)
GA-Z77MX-D3H (rev. 1.1)
GA-Z77M-D3H-MVP (rev. 1.0)
GA-Z77M-D3H-MVP (rev. 1.1)
GA-Z77M-D3H (rev. 1.0)
GA-Z77M-D3H (rev. 1.1)
GA-Z77N-WIFI (rev. 1.0)

Congrats 👍

**Comment by al3xtjames** [comment]
Interestingly enough, the update also has NVMe support (AMI's NVMe drivers are included). lol, they still haven't fixed ThinkPwn on the majority of them (excluding UD5H), although that isn't too useful when write protection isn't present.

**Comment by RamKromberg** [comment]
I didn't know about the NVMe support and was actually looking into adding it following https://www.win-raid.com/t871f16-Guide-How-to-get-full-NVMe-support-for-all-Systems-with-an-AMI-UEFI-BIOS.html so thanks! 

Well, regardless if some private customer bulk ordered UD5Hs and 5+ years LTS and got the fixed MATS tables that way, or a couple of gigabyte engineers running the board on their home PCs needed patching them up for personal use, I think it's definitely a followup on your blog.

**Comment by mr-an** [comment]
This Gigabyte Support Team Representative seemed less than enthused about the idea of NVMe on  GA-Z77X-UD5H:

Question: | But the F16j bios supports nvme. Why does it do that if you cannot use the moterboard with an nvme drive through an adapter? | 2/12/2018 7:59 PM

Answer: | Dear customer,Where  get information bios F16j support NVMe ?  Information posted F16j is  for Adjust MATS table to improve OS compatibility ( Multiple Application  Tracking System ) only. You may check it on website link below:https://www.gigabyte.com/Motherboard/GA-Z77X-UD5H-rev-11#support-dlBest regards,  GIGABYTE technical support team.

I saw it here:https://github.com/al3xtjames/coreboot_mainboard_gigabyte_ga-z77x-ud5h/issues/2 

Answer: | Dear customer,It was forums discuss page for F16j MATS stable bios, it wasn't Gigabyte official website. M.2 not validated on this old chipset. board.  

Best regards,       GIGABYTE technical support team. | 2/13/2018 6:56 PM
